daemon:
  bind: 127.0.0.1
  port: 8888
  http:
    pipe: true
    vars: true
  load:
    - /etc/deploy42/conf.d/*.yml

namespaces:
  - endpoint: andrerocker/restrict
    chaining:
      - cas_tickets
      - ip_restriction
      - service_knocking
    commands:
      process:
        - get: ps -ef | grep {process}
          put: kill {process}
          delete: kill -9 {process}

  - endpoint: andrerocker
    commands:
      log:
        - get: tail -f /tmp/1
