daemon:
  bind: 127.0.0.1
  port: 8888
  http:
    pipe: false
    vars: false
  load:
    - /etc/deploy42/conf.d/*.yml

namespaces:
  - endpoint: andrerocker/restrict
    chaining:
      - cas_ticket
      - ip_restriction
      - service_knocking
    commands:
      pkg:
        - get: apt-cache show {pkg}
          put: apt-get update && apt-get install -y {pkg}
          delete: apt-get remove --purge {pkg}

  - endpoint: andrerocker
    commands:
      log:
        - get: tail -f /tmp/1
    
