daemon:
  bind: 127.0.0.1
  port: 8888

commands:
  pkg:
    - get: apt-cache show kdaoskdoasodas
      put: apt-get update && apt-get install -y kdaoskdoasd
      delete: apt-get remove --purge kdoaksodsaod

  process:
    - get: ps -ef | grep {process}
      put: kill {process}
      delete: kill -9 {process}

  log:
    - get: tail -f kdoaksdoaksod
